"""
RetailSense AI — Pydantic Schemas for Structured LLM Outputs & Reasoning

Enforces strict separation of:
1. Factual data (Database / Tools)
2. Model predictions (ML Models)
3. Retrieved knowledge (RAG Documents)
4. Generated explanation (LLM Narrative)
"""

from datetime import datetime
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field, ConfigDict


class FactualData(BaseModel):
    """Factual data fetched directly from database tables or verified tools."""
    model_config = ConfigDict(protected_namespaces=())
    source: str = Field(..., description="Database table or tool name (e.g. database.inventory, tools.get_inventory)")
    metrics: Dict[str, Any] = Field(..., description="Numerical and status metrics from authoritative DB/tool")


class ModelPrediction(BaseModel):
    """Predictive data generated by trained ML models (XGBoost / Random Forest)."""
    model_config = ConfigDict(protected_namespaces=())
    model_name: str = Field(..., description="Name of deployed ML model")
    prediction_horizon_days: int = Field(..., description="Forecast horizon in days")
    predicted_units: float = Field(..., description="Total forecasted demand units from ML model")
    evaluation_metrics: Dict[str, float] = Field(..., description="Model validation metrics (MAE, RMSE, R2, MAPE)")


class RetrievedKnowledge(BaseModel):
    """Contextual knowledge retrieved via RAG vector search or policy documents."""
    model_config = ConfigDict(protected_namespaces=())
    document_id: str = Field(..., description="Unique document chunk or policy ID")
    title: str = Field(..., description="Document title")
    excerpt: str = Field(..., description="Relevant text excerpt retrieved")


class DecisionExplanation(BaseModel):
    """
    Structured LLM Decision & Reasoning Schema for Retail Operations.
    Guarantees no numerical fabrication by binding metrics directly to supporting_data & model_predictions.
    """
    model_config = ConfigDict(protected_namespaces=())
    decision: str = Field(..., description="High-level operational decision summary")
    reasoning_summary: str = Field(..., description="Step-by-step reasoning narrative")
    supporting_data: FactualData = Field(..., description="Authoritative factual DB/tool metrics")
    model_predictions: Optional[ModelPrediction] = Field(None, description="ML demand forecast metrics")
    retrieved_knowledge: List[RetrievedKnowledge] = Field(default_factory=list, description="RAG policy/knowledge chunks")
    sources: List[str] = Field(..., description="List of authoritative data sources used")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    recommended_action: str = Field(..., description="Clear recommended action plan for Seller, Customer, or Admin")
    generated_explanation: str = Field(..., description="Natural language explanation synthesized for human user")


class GoalInterpretation(BaseModel):
    """Structured LLM Goal NLU Output."""
    model_config = ConfigDict(protected_namespaces=())
    original_goal: str
    task_category: str
    target_entities: Dict[str, Any]
    required_agents: List[str]


class LLMAuditMetadata(BaseModel):
    """Audit metadata tracking every LLM invocation for auditability."""
    model_config = ConfigDict(protected_namespaces=())
    call_id: str = Field(..., description="Unique LLM invocation ID")
    model_name: str = Field(..., description="LLM model identifier")
    task_name: str = Field(..., description="Name of LLM task (e.g. goal_interpretation, explanation_generation)")
    prompt_template: str = Field(..., description="Prompt template used")
    response_timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    latency_ms: float = Field(..., description="LLM execution time in milliseconds")
    tokens_used: Dict[str, int] = Field(..., description="Token usage breakdown (prompt_tokens, completion_tokens, total_tokens)")
